// ═══ SSE ═══
var _currentTask=null;
(function(){
  try{var e=null,t=null;
    var lastTskRef=0,lastHomeRfsh=0;
    // 实时刷新断点任务列表（仅当任务页已渲染 #tab-tasks 时才刷新，避免报错）
    function rfshTasks(){try{if(document.getElementById('tab-tasks'))Rplg()}catch(e){}}
    function rfshTasksThrottled(){var now=Date.now();if(now-lastTskRef>=2000){lastTskRef=now;rfshTasks()}}
    // 首页任务列表刷新同样限流：task_progress 每放一个方块就触发一次，无限流=每方块发一次 HTTP+重渲染
    function rfshHomeThrottled(){var now=Date.now();if(now-lastHomeRfsh>=2000){lastHomeRfsh=now;if(curTab==='home')refreshHomeTasks()}}
    function c(){
    if(e)e.close();e=new EventSource('/stream');e.onopen=function(){A('GET','/api/bot/status').then(function(s){U(s.ok&&s.connected, s.ok&&s.is_op)})};
    e.addEventListener('plugin_update', function(){ if(document.getElementById('tab-tasks')) Rplg(); });
    e.onerror=function(){clearTimeout(t);t=setTimeout(c,3000)};
    e.addEventListener('progress',function(v){try{var d=JSON.parse(v.data);addL(d.msg)}catch(e){}});
    e.addEventListener('task_start',function(v){var d=JSON.parse(v.data);_currentTask={type:d.type,progress:0};addL('[启动] '+d.type);rfshTasks();if(curTab==='home')refreshHomeTasks()});
    e.addEventListener('task_done',function(v){var d=JSON.parse(v.data);_currentTask=null;var mp=document.getElementById('imp-multi-pg');if(mp)mp.classList.add('gone');addL(ICONS.check+' 完成 '+(d.msg||''),'o');T(d.msg||'任务完成','o');resetTaskButtons();rfshTasks();if(curTab==='home')refreshHomeTasks();cbFinalizeImport(true,d.msg)});
    e.addEventListener('task_error',function(v){var d=JSON.parse(v.data);_currentTask=null;var mp=document.getElementById('imp-multi-pg');if(mp)mp.classList.add('gone');addL(ICONS.x+' 错误 '+(d.error||''),'e');T(d.error||'任务失败','e');resetTaskButtons();rfshTasks();if(curTab==='home')refreshHomeTasks();cbFinalizeImport(false,d.error)});
    e.addEventListener('task_progress',function(v){var d=JSON.parse(v.data);rfshTasksThrottled();if(d.progress!=null){if(_currentTask)_currentTask.progress=d.progress;var b=document.getElementById('imp-bar')||document.getElementById('exp-bar')||document.getElementById('md-bar')||document.getElementById('cb-import-bar');if(b)b.style.width=(d.progress*100)+'%';var cbp=document.getElementById('cb-import-pct');if(cbp)cbp.textContent=Math.round(d.progress*100)+'%'};if(d.multi){var mp=document.getElementById('imp-multi-pg');if(mp){mp.classList.remove('gone');document.getElementById('imp-pg').classList.add('gone')};var u=function(id,pct){var el=document.getElementById(id);if(el)el.style.width=pct+'%'};u('mp-bar-normal',(d.multi.normal||0)*100);u('mp-bar-nbt',(d.multi.nbt||0)*100);u('mp-bar-sign',(d.multi.sign||0)*100);['normal','nbt','sign'].forEach(function(k){var el=document.getElementById('mp-pct-'+k);if(el)el.textContent=Math.round((d.multi[k]||0)*100)+'%'})};rfshHomeThrottled()});e.addEventListener('clear_progress',function(v){var d=JSON.parse(v.data);if(d.progress!=null){var b=document.getElementById('clear-bar');var p=document.getElementById('clear-pg');var s=document.getElementById('clear-stat');if(b)b.style.width=(d.progress*100)+'%';if(p)p.classList.remove('gone');if(s){s.classList.remove('gone');s.textContent='清空中 '+(d.cleared||0)+' / '+(d.total||0)+' 方块'}};var ipg=document.getElementById('imp-pg');if(ipg)ipg.classList.add('gone');var ist=document.getElementById('imp-stat');if(ist)ist.classList.add('gone')});e.addEventListener('clear_done',function(v){var b=document.getElementById('clear-bar');var p=document.getElementById('clear-pg');var s=document.getElementById('clear-stat');if(b)b.style.width='100%';if(p)p.classList.add('gone');if(s)s.classList.add('gone');var ipg=document.getElementById('imp-pg');if(ipg)ipg.classList.remove('gone');var ist=document.getElementById('imp-stat');if(ist)ist.classList.remove('gone')});
    e.addEventListener('bot_log',function(v){var d=JSON.parse(v.data);var cl=document.getElementById('conn-log');if(cl){var de=document.createElement('div');de.innerHTML=renderLogLine(d.msg);cl.appendChild(de);capLogDom(cl,300);cl.scrollTop=cl.scrollHeight}else{addL(d.msg)}var s=document.getElementById('conn-stage');if(s){var m=d.msg;if(m.indexOf('已连接到服务器')>=0)s.textContent='已连接，初始化中...';else if(m.indexOf('心跳已启动')>=0)s.textContent='心跳就绪，等待权限...';else if(m.indexOf('命令验证通过')>=0||m.indexOf('成功完成初始化')>=0){s.textContent='权限已确认，完成初始化！';var el=document.getElementById('conn-modal');if(el)el.remove();T('已连接','o');A('GET','/api/bot/status').then(function(st){U(true,st.is_op);if(curTab==='home')Rhome()})}else if(m.indexOf('命令验证失败')>=0){s.textContent='无权限，等待管理员授权...'}else if(m.indexOf('验证超时')>=0){s.textContent='验证超时，重试中...'}else if(m.indexOf('请求管理员授权')>=0)s.textContent='等待管理员授权...';else if(m.indexOf('疑似 OP 包')>=0)s.textContent='检测到权限信号，验证中...';else if(m.indexOf('尝试连接')>=0)s.textContent='正在连接服务器(重试)...';else if(m.indexOf('初始化心跳')>=0)s.textContent='初始化心跳...';else if(m.indexOf('监听器已启动')>=0)s.textContent='包监听就绪，等待权限...';else if(m.indexOf('排空')>=0)s.textContent='处理登录缓存...';else if(m.indexOf('已重试')>=0&&(m.indexOf('登录失败')>=0||m.indexOf('连接失败')>=0)){var el=document.getElementById('conn-modal');if(el)el.remove();T('连接失败: '+m,'e')}}});e.addEventListener('conn_ready',function(v){var el=document.getElementById('conn-modal');if(el){el.remove();T('已连接','o')}A('GET','/api/bot/status').then(function(st){U(true,st.is_op);if(curTab==='home')Rhome();else updateConnStatus(true,st.is_op)})});
    e.addEventListener('music_start',function(v){var d=JSON.parse(v.data);addL('[音乐] '+d.total_notes+' 音符, 约'+(d.title||'')+' '+d.estimated_duration)});
    e.addEventListener('music_progress',function(v){var d=JSON.parse(v.data);muCurrent=d.current;muTotal=d.total;var pct=d.total>0?Math.round(d.current/d.total*100):0;var bar=document.getElementById('mu-bar');if(bar)bar.style.width=pct+'%';var stat=document.getElementById('mu-stat');if(stat){var name=muPath?muPath.replace(/\.[^.]+$/,''):'未知';var extra='';if(muQueueActive&&muQueueIndex>=0&&muQueue[muQueueIndex]){name=muQueue[muQueueIndex].title||name;extra='<span style="margin-left:6px;color:var(--phx-primary);font-size:10px">' + ICONS.musicNote + ' '+(muQueueIndex+1)+'/'+muQueue.length+'</span>'};stat.innerHTML='<div style="font-weight:600;font-size:13px">'+escHtml(name)+'</div><div style="font-size:11px;color:var(--phx-text-secondary);margin-top:2px">'+pct+'%'+extra+'</div>'}});
    e.addEventListener('music_done',function(v){addL('[音乐] 播放完成','o');if(muQueueActive){muQueueActive=false;muQueueIndex=-1;renderQueueUI();document.getElementById('mu-queue-controls')?.classList.add('gone')}else{resetMusicUI()};T('播放完成','o')});
    e.addEventListener('queue_update',function(v){var d=JSON.parse(v.data);if(!d)return;muQueue=d.queue||[];muQueueIndex=d.current!=null?d.current:-1;muQueueActive=d.active||false;muLoopMode=d.loop_mode||'none';updateLoopBtn();renderQueueUI();var qc=document.getElementById('mu-queue-controls');if(qc)qc.classList.toggle('gone',!muQueue.length);var qcard=document.getElementById('mu-queue-card');if(qcard)qcard.classList.toggle('gone',!muQueue.length)});
    e.addEventListener('track_change',function(v){var d=JSON.parse(v.data);if(!d)return;muQueueIndex=d.index;muPath=d.cache_key;muPlaying=true;muPaused=false;muCurrent=0;renderQueueUI();setPlayingUI();var stat=document.getElementById('mu-stat');if(stat){var extra='<span style="margin-left:6px;color:var(--phx-primary);font-size:10px">' + ICONS.musicNote + ' '+(d.index+1)+'/'+d.total+'</span>';stat.innerHTML='<div style="font-weight:600;font-size:13px">'+escHtml(d.title||'')+'</div><div style="font-size:11px;color:var(--phx-text-secondary);margin-top:2px">0%'+extra+'</div>'};addL('[音乐] 播放: '+escHtml(d.title||d.cache_key),'o')});
    e.addEventListener('version_check',function(v){var d=JSON.parse(v.data);handleVersionCheck(d)});
    e.addEventListener('announcements',function(v){if(window.wzActive)return;var d=JSON.parse(v.data);if(d.announcements)showAnnouncements(d.announcements)});
    e.addEventListener('notify',function(v){var d=JSON.parse(v.data);if(typeof renderNotification==='function')renderNotification(d)});
    e.addEventListener("integrity_alert",function(v){var d=JSON.parse(v.data);if(!d.passed)showIntegrityAlert(d)});
    e.addEventListener("pos",function(v){var d=JSON.parse(v.data);flyState.x=d.x;flyState.y=d.y;flyState.z=d.z;flyState.pitch=d.pitch;flyState.yaw=d.yaw;flyUpdateDisplay()});
    e.addEventListener("draw_update",function(v){var d=JSON.parse(v.data);if(typeof onDrawUpdate==='function')onDrawUpdate(d)});
    e.addEventListener("draw_plane",function(v){var d=JSON.parse(v.data);if(typeof onDrawPlane==='function')onDrawPlane(d)});
    e.addEventListener("draw_busy",function(v){var d=JSON.parse(v.data);if(typeof onDrawBusy==='function')onDrawBusy(d)});
    e.addEventListener("draw_error",function(v){var d=JSON.parse(v.data);if(typeof onDrawError==='function')onDrawError(d)});
    e.addEventListener("draw_sync",function(v){var d=JSON.parse(v.data);if(typeof onDrawSync==='function')onDrawSync(d)});
    e.addEventListener('parse_progress',function(v){try{var d=JSON.parse(v.data);if(!d||!document.getElementById('parse-modal'))return;var t=d.total||0;var pct=t>0?Math.min(100,Math.round((d.processed||0)/t*100)):0;var b=document.getElementById('parse-bar');if(b){if(pct>0){b.classList.remove('indeterminate');b.style.width=pct+'%'}else{b.classList.add('indeterminate')}}var p=document.getElementById('parse-pct');if(p)p.textContent=pct>0?(pct+'%'):'解析中…'}catch(e){}});
    e.addEventListener('parse_done',function(){var m=document.getElementById('parse-modal');if(m)m.classList.add('gone')});
    e.addEventListener('parse_canceled',function(){var m=document.getElementById('parse-modal');if(m)m.classList.add('gone');T('解析已终止','o')});
    e.addEventListener('parse_error',function(v){var d=JSON.parse(v.data);var m=document.getElementById('parse-modal');if(m)m.classList.add('gone');T('解析失败: '+(d&&d.error||'未知'),'e')})
  }}catch(e){}c();

  function addL(m,cl){allLogs.push({msg:m,cl:cl});capLogs(500);var ids=['imp-log','exp-log','ma-log','mu-log','md-log','conn-log','console-log'];var l=null;for(var i=0;i<ids.length;i++){var el=document.getElementById(ids[i]);if(el&&el.offsetParent!==null){l=el;break}}if(!l){for(var i=0;i<ids.length;i++){var el=document.getElementById(ids[i]);if(el){l=el;break}}}if(!l)return;var d=document.createElement('div');d.innerHTML=renderLogLine(m);if(l.id==='console-log'){if(cl==='e')d.style.color='#ff5555';if(typeof _consoleRendered!=='undefined')_consoleRendered++}else{if(cl)d.className=cl==='o'?'cl-ok':cl==='e'?'cl-err':''}l.appendChild(d);capLogDom(l,300);l.scrollTop=l.scrollHeight}
})();
